df = read.csv('realestate_data.csv')
df
#summary of the data set 
summary(df)

#sum of the NA Values in the data set
sum(is.na(df))
#here we are seeing the names of the data set column names
colnames(df)


#here is the loop that is checking ,replacing and removing the NA values from the Data Frame

for (i in which(sapply(df, is.numeric))) {
  df[is.na(df[, i]), i] = mean(df[, i],  na.rm = TRUE)
}


#here is new data frame which  omitting the NA values here another technique the remove NA values from the data set 
newdf = na.omit(df)

#The next major preprocessing activity is to identify the outliers package and deal with it. We can identify the presence of outliers in R by making use of the outliers function. We can use the function outliers only on the numeric columns, hence let's consider the preceding dataset, where the NAs were replaced by the mean values, and we will identify the presence of an outlier using the outliers function. Then, we get the location of all the outliers using the which function and finally, we remove the rows that had outlier values

install.packages("outliers")
library(outliers)

#We identify the outliers in the X2012 column, which can be subsetted using the data$X2012 command

outlier_tf = outlier(newdf$grade,logical=TRUE)
sum(outlier_tf)



#What were the outliers
find_outlier = which(outlier_tf==TRUE,arr.ind=TRUE)
#Removing the outliers
newdata = newdf[-find_outlier,]
nrow(newdata)

#finding the Standard Deaviation of Price Column 
standard_deviation = sd(newdf$price)
paste("Std Deviation of MPG:", standard_deviation)



#------------------------Rgression with single Variable--------------------------------



#declare the variable and get values from the data set seprately
x = df$sqft_living15 #its become the independent variable in leaning model
y = df$price  #its going to be predicted or dependent variable

# Apply the lm() function.
relation = lm(y~x)

#print the relation generated by the lm function and summary of the relation variable
print(relation)
print(summary(relation)) #R square value is 0.34 means it gives 34% of accuracy

#here is data and frame is two functions and having x variable with value of row of 'sqft_living15'
a = data.frame(x = 1340)
result =  predict(relation,a) #going to predict the price on the basis of sqft_living15 value 
print(result) 


#ploting the graph of the variable

# Give the chart file a name.
png(file = "linearregression.png")
# Plot the chart.
plot(y,x,col = "blue",main = "price  & sqft_living15",
     abline(lm(x~y)),cex = 1.3,pch = 16,xlab = "price",ylab = "sqft_living15")
# Save the file.
dev.off()


#------------------------Multiple Linear Regression--------------------------------

# 
# Following is the description of the parameters used −
# 
# y is the response variable.
# 
# a, b1, b2...bn are the coefficients.
# 
# x1, x2, ...xn are the predictor variables.
# 
# We create the regression model using the lm() function in R. The model determines the value of the coefficients using the input data. Next we can predict the value of the response variable for a given set of predictor variables using these coefficients.
# 
# lm() Function
# This function creates the relationship model between the predictor and the response variable.
# 
# Syntax
# The basic syntax for lm() function in multiple regression is




colnames(df)
new_df = df[,c("price","bedrooms","bathrooms","sqft_living","sqft_lot","floors","waterfront","view","condition","grade","sqft_above","yr_built","sqft_living15","sqft_lot15")]
model <- lm(price~bedrooms+bathrooms+sqft_living+sqft_lot+floors+waterfront+view+condition+grade+sqft_above+yr_built+sqft_living15+sqft_lot15, data = new_df)
summary(model) #here Rsquared is 65%
# Show the model.
model

cat("# # # # The Coefficient Values # # # ","\n")
Xprice = coef(model)[1]
print(Xprice)
Xbedrooms = coef(model)[2]
print(Xbedrooms)
Xbathrooms = coef(model)[3]
print(Xbathrooms)
Xsqft_living = coef(model)[4]
print(Xsqft_living)
Xsqft_lot = coef(model)[5]
print(Xsqft_lot)
Xfloors = coef(model)[6]
print(Xfloors)
Xwaterfront = coef(model)[7]
print(Xwaterfront)
Xview = coef(model)[8]
print(Xview)
Xcondition = coef(model)[9]
print(Xcondition)
Xgrade = coef(model)[10]
print(Xgrade)
Xsqft_above = coef(model)[11]
print(Xsqft_above)
Xsqft_basement = coef(model)[12]
print(Xsqft_basement)
Xyr_built = coef(model)[13]
print(Xyr_built)
Xsqft_living15 = coef(model)[14]
print(Xsqft_living15)
Xsqft_lot15 = coef(model)[15]
print(Xsqft_lot15)
 
# Y = a+Xdisp.x1+Xhp.x2+Xwt.x3
# here is the formula

Y=(6311960.373850)+(-39458.662313)*3+(46937.370742)*1.0+(46937.370742)*1180+(46937.370742)*5650+(167.009569)*1.0+(-0.002682)*0+(27258.818309)*0+(581782.787088)*3+(43398.984884)*7+(18442.412429)*1180+(119845.393906)*1955+(-6.128757)*1340+(-3628.578851)*560

Y

cat(sprintf("\"%f\" \"%f\"\"%f\" \"%f\"\"%f\" \"%f\"\"%f\" \"%f\"\"%f\" \"%f\"\"%f\" \"%f\"\"%f\"\n",Xprice,Xbedrooms,Xbathrooms,Xsqft_living,Xsqft_lot,Xfloors,Xwaterfront,Xview,Xcondition,Xgrade,Xsqft_above,Xsqft_basement,Xyr_built,Xsqft_living15,Xsqft_lot15))


